### ISSUE TITLE
Quest: The Lost Gem

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3302]
The tentacles do not drop the quest item. The Gem. I have killed 50 of them.

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/quest=26464/the-lost-gem

**Comment by Malae1** [comment]
Fixed in next update

**Comment by tribaljet** [comment]
When accepting this quest, the quest item Glowing Gem is given automatically and does not mark the quest as completed. The player is required to destroy the item in order to get it from a mob drop.

**Comment by Tregeta** [comment]
You likely took either one of these quests giving them item:
http://www.wowhead.com/quest=13645/to-raene-wolfrunner
http://www.wowhead.com/quest=26476/dryad-delivery
Since the quest requirement chain is not set up, this is most definitely going to be the cause.

**Comment by ATalisan** [comment]
Still having that problem with the Glowing Gem not dropping from the tendrils.
I did have quest 13645 (raene wolfrunner) and the Glowing Gem, destroyed it and abandoned the quest, still no drops.
Tried logging and again, still cannot get the tentacles to drop the Glowing Gem.

**Comment by Tregeta** [comment]
Unable to reproduce, please make sure you are not in a raid group and are on the correct quest.

**Comment by Ardente47** [comment]
Just do what tribaljet wrote. Worked perfectly fine.

Nontheless the quest needs to be fixed, so you don't have to destroy the auto obtained Gem inorder to collect it from the quest mobs.
